using System.Reflection;
[assembly: AssemblyTitle("Mapbox.Vector.Tile")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Mapbox.Vector.Tile")]
[assembly: AssemblyCopyright("Copyright ©bertt 2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("3.1.1.0")]
[assembly: AssemblyFileVersion("3.1.1.0")]
